Article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor', include('ckeditor_uploader.urls')),
                  path('account/', include('account.urls', namespace='account')),
                  path('', include('main.urls', namespace='main'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('blog/<blog_id>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('category/<category_id>/', views.CategoryView.as_view(), name='category'),
    path('404/', views.NotFoundView.as_view(), name='404'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.CantactView.as_view(), name='contact')

]

main/models.py
from django.db import models


# Create your models here.
class MainSeo(models.Model):
    SEO_TYPE = (('name', 'name'), ('property', 'property'))
    type = models.CharField(choices=SEO_TYPE, max_length=120)
    title = models.CharField(max_length=2000)
    content = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'seo اصلی'
        verbose_name_plural = 'seo اصلی'

main/forms.py
from django import forms


class ArticleForm(forms.Form):
    q = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'type': "text", 'class': "nav__search-input", 'placeholder': "جستجو مقالات"
    }))

main/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.views.generic import View
from Blog.models import *
from Blog.forms import *
from site_settings.models import SiteSettings, SocialMedia
from main.forms import ArticleForm
from django.contrib import messages
from main.models import MainSeo


def media_url(request):
    return {'media_url': settings.MEDIA_URL}


class IndexView(View):
    template_name = 'page/main/index.html'

    def get(self, request):
        main_seo = MainSeo.objects.all()
        blogs = Blog.objects.filter(is_active=True).order_by('created_date')
        blog_view = Blog.objects.filter(is_active=True).order_by('-view_count')[:5]
        blog_views = Blog.objects.filter(is_active=True).order_by('-view_count')[:10]
        tags = BlogTag.objects.filter(blog__in=blogs)
        categories = BlogCategory.objects.all()
        category = BlogCategory.objects.all().order_by('-created_date')[:4]

        blog_category = []
        for cate in category:
            for blog in blogs.filter(category=cate):
                blog_category.append(blog)
        blog = Blog.objects.filter(is_active=True)[:4]
        selected_blog = Blog.objects.filter(selected=True, is_active=True).order_by('created_date')[:2]
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()

        top_best = Blog.objects.filter(is_active=True).order_by('-view_count')[:1]
        top = Blog.objects.filter(is_active=True, top=True).order_by('-view_count')[:3]
        form = ArticleForm()
        context = {
            'media_url': settings.MEDIA_URL,
            'blogs': blogs,
            'tags': tags,
            'blog_view': blog_view,
            'category': categories,
            'blog_views': blog_views,
            'blog_category': blog_category,
            'blog': blog,
            'selected_blog': selected_blog,
            'social_media': social_media,
            'top_best': top_best,
            'top': top,
            'form': form,
            'site_settings': site_setting,
            'main_seo': main_seo,
            'category_bottom':category
        }
        return render(request, self.template_name, context)


class SearchView(View):
    template_name = 'page/main/search.html'

    def get(self, request, *args, **kwargs):
        query = request.GET['q']
        blogs = Blog.objects.filter(title__icontains=query, is_active=True)
        blog_view = Blog.objects.filter(is_active=True).order_by('-view_count')[:5]
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        context = {
            'media_url': settings.MEDIA_URL,
            'blogs': blogs,
            'blog_view': blog_view,
            'site_settings': site_setting,
            'social_media': social_media
        }
        return render(request, self.template_name, context)


class BlogDetailView(View):
    template_name = 'page/main/blog_detail.html'

    def get(self, request, blog_id):
        form = CommentForm()
        try:
            blog = Blog.objects.get(id=blog_id)
        except Blog.DoesNotExist:
            messages.error(request, 'مقاله مورد نظر یافت نشد')
            return redirect('main:404')
        comments = BlogComment.objects.filter(blog=blog, is_active=True)
        comment_count = comments.count()
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        blog_view = Blog.objects.filter(is_active=True).order_by('-view_count')[:5]

        blog_category = Blog.objects.filter(category=blog.category)
        blog.view_count += 1
        blog.save()
        blog_seo = BlogSeo.objects.all()
        context = {
            'media_url': settings.MEDIA_URL,
            'blog': blog,
            'blog_category': blog_category,
            'form_comment': form,
            'comments': comments,
            'comment_count': comment_count,
            'social_media': social_media,
            'blog_view': blog_view,
            'site_settings': site_setting,
            'blog_seo': blog_seo
        }
        return render(request, self.template_name, context)

    def post(self, request, blog_id):
        form = CommentForm(request.POST)
        user = request.user
        blog = Blog.objects.get(id=blog_id)
        if form.is_valid():
            title = form.cleaned_data['title']
            comment = form.cleaned_data['comment']
            if user.is_authenticated:
                BlogComment.objects.create(author=user, comment=comment, blog=blog, title=title)
                messages.success(request, 'کامنت شما با موفقیت ثبت شد')
                return redirect('main:blog_detail', blog_id=blog.id)
            else:
                messages.error(request, 'ابتدا با ثبت نام کنید!!')
                return redirect('account:login')
        else:
            messages.error(request, 'فرم نامعتبر است')
            return redirect('main:blog_detail', blog_id=blog.id)


class CategoryView(View):

    def get(self, request, category_id):
        try:
            category = BlogCategory.objects.get(id=category_id)
        except BlogCategory.DoesNotExist:
            messages.error(request, 'دسته بندی یافت نشد')
            return redirect('main:404')
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        blog_view = Blog.objects.filter(is_active=True).order_by('-view_count')[:5]
        if category:
            context = {
                'category': category,
                'media_url': settings.MEDIA_URL,
                'social_media': social_media,
                'blog_view': blog_view,
                'site_settings': site_setting
            }
            return render(request, 'page/main/categories.html', context)


# region notfound
class NotFoundView(View):
    def get(self, request):
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        context = {
            'media_url': settings.MEDIA_URL,
            'social_media': social_media,
            'site_settings': site_setting
        }
        return render(request, 'page/main/404.html', context)


# endregion


class AboutView(View):
    def get(self, request):
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        context = {
            'media_url': settings.MEDIA_URL,
            'social_media': social_media,
            'site_settings': site_setting
        }
        return render(request, 'page/main/about.html', context)


class CantactView(View):
    def get(self, request):
        site_setting = SiteSettings.objects.all().first()
        social_media = SocialMedia.objects.all()
        context = {
            'media_url': settings.MEDIA_URL,
            'social_media': social_media,
            'site_settings': site_setting
        }
        return render(request, 'page/main/contact.html', context)

templates/page/main/about.html
{% extends 'parent/base.html' %}
{% block title %}
    درباره ما
{% endblock %}

{% block content %}
    <!-- Breadcrumbs -->
    <div class="container">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">خانه</a>
            </li>
            <li class="breadcrumbs__item breadcrumbs__item--current">
                درباره ما
            </li>
        </ul>
    </div>

    <div class="main-container container" id="main-container">
        <!-- post content -->
        <div class="blog__content mb-72">
            <h1 class="page-title">درباره ما</h1>
            <img src="{{ media_url }}img/content/about/about_bg.jpg" class="page-featured-img">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="entry__article">
                        {{ site_settings.about_us |safe }}
                    </div>
                </div>
            </div>
        </div> <!-- end post content -->
    </div> <!-- end main container -->
{% endblock %}

templates/page/main/blog_detail.html
{% extends 'parent/base.html' %}

{% block title %}
    جزییات مقاله
{% endblock %}
{% block seo %}
    {% if blog_seo.type == name %}
        {% for seo in blog_seo %}
            <meta name="{{ seo.title }}" content="{{ seo.content }}">
        {% endfor %}
    {% elif blog_seo.type == property %}
        {% for seo in blog_seo %}
            <meta property="{{ seo.title }}" content="{{ seo.content }}">
        {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">خانه</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">اخبار</a>
            </li>
            <li class="breadcrumbs__item breadcrumbs__item--current">
                تکنولوژی
            </li>
        </ul>
    </div>
    <div class="main-container container" id="main-container">


        <div class="row">

            <div class="col-lg-8 blog__content mb-72">
                <div class="content-box">

                    <!-- standard post -->
                    <article class="entry mb-0">

                        <div class="single-post__entry-header entry__header">
                            <a href="{% url 'main:category' blog.category.id %}"
                               class="entry__meta-category entry__meta-category--label entry__meta-category--green">
                                {{ blog.category }}
                            </a>
                            <h1 class="single-post__entry-title">
                                {{ blog.title }}
                            </h1>

                            <div class="entry__meta-holder">
                                <ul class="entry__meta">
                                    <li class="entry__meta-author">
                                        <span>نویسنده:</span>
                                        <a>{{ blog.author }}</a>
                                    </li>
                                    <li class="entry__meta-date">
                                        {{ blog.published_date }}
                                    </li>
                                </ul>

                                <ul class="entry__meta">
                                    <li class="entry__meta-views">
                                        <i class="ui-eye"></i>
                                        <span>{{ blog.view_count }}</span>
                                    </li>
                                    <li class="entry__meta-comments">
                                        <a>
                                            <i class="ui-chat-empty"></i>{{ comment_count }}
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div> <!-- end entry header -->

                        <div class="entry__img-holder">
                            <img src="img/content/thumb/post-8.jpg" alt="" class="entry__img">
                        </div>

                        <div class="entry__article-wrap">


                            <div class="entry__article">
                                {{ blog.text | safe }}
                            </div> <!-- end entry article -->
                        </div> <!-- end entry article wrap -->
                        <div class="entry__tags">
                            <i class="ui-tags"></i>
                            <span class="entry__tags-label">برچسب ها:</span>
                            {% for tag in blog.tag_blog.all %}
                                <a>{{ tag.tag_name }}</a>
                            {% endfor %}
                        </div>

                        <!-- Author -->
                        <div class="entry-author clearfix">
                            <img alt="" data-src="{{ blog.author.image.url }}" src="{{ blog.author.image.url }}"
                                 class="avatar lazyload">
                            <div class="entry-author__info">
                                <h6 class="entry-author__name">
                                    <a>{{ blog.author }}</a>
                                </h6>
                                <p class="mb-0">{{ blog.author.description | safe }}</p>
                            </div>
                        </div>

                        <!-- Related Posts -->
                        <section class="section related-posts mt-40 mb-0">
                            <div class="title-wrap title-wrap--line">
                                <h3 class="section-title">مطالب مرتبط</h3>
                            </div>

                            <!-- Slider -->
                            <div id="owl-posts-3-items" class="owl-carousel owl-theme owl-carousel--arrows-outside">
                                {% for blog in blog_category %}
                                    <article class="entry thumb thumb--size-1">
                                        <div class="entry__img-holder thumb__img-holder"
                                             style="background-image: url({{ blog.cover_image.url }});">
                                            <div class="bottom-gradient"></div>
                                            <div class="thumb-text-holder">
                                                <h2 class="thumb-entry-title">
                                                    <a href="{% url 'main:blog_detail' blog.id %}">{{ blog.title }}</a>
                                                </h2>
                                            </div>
                                            <a href="{% url 'main:blog_detail' blog.id %}" class="thumb-url"></a>
                                        </div>
                                    </article>
                                {% endfor %}
                            </div> <!-- end slider -->

                        </section> <!-- end related posts -->

                    </article> <!-- end standard post -->

                    <!-- Comments -->
                    <div class="entry-comments">
                        <div class="title-wrap title-wrap--line">
                            {% if comment_count > 0 %}
                                <h3 class="section-title">{{ comment_count }} دیدگاه</h3>
                            {% else %}
                                <h3 class="section-title">فعلا دیدگاهی وجود ندارد</h3>
                            {% endif %}

                        </div>
                        <ul class="comment-list">
                            {% for comment in comments %}
                                <li class="comment">
                                    <div class="comment-body">
                                        <div class="comment-avatar">
                                            <img alt="" src="{{ comment.author.image.url }}">
                                        </div>
                                        <div class="comment-text">
                                            <h6 class="comment-author">{{ comment.author }}</h6>
                                            <div class="comment-metadata">
                                                <a class="comment-date">{{ comment.published_date }}</a>
                                            </div>
                                            <p>{{ comment.title }}</p>
                                            <p>{{ comment.comment | safe }}</p>

                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div> <!-- end comments -->

                    <!-- Comment Form -->
                    <div id="respond" class="comment-respond">
                        <div class="title-wrap">
                            <h5 class="comment-respond__title section-title">دیدگاه شما</h5>
                        </div>
                        <form id="form" class="comment-form" method="post"
                              action="{% url 'main:blog_detail' blog.id %}">
                            {% csrf_token %}
                            <p class="comment-form-comment">
                                <label for="comment">دیدگاه</label>
                                {{ form_comment.comment }}
                            </p>

                            <div class="row row-20">
                                <div class="col-lg-4">
                                    <label for="name">عنوان: *</label>
                                    {{ form_comment.title }}
                                </div>

                            </div>

                            <p class="comment-form-submit">
                                <button type="submit" class="btn btn-lg btn-color btn-button"
                                >ارسال دیدگاه
                                </button>
                            </p>

                        </form>
                    </div> <!-- end comment form -->

                </div> <!-- end content box -->
            </div> <!-- end post content -->

            <!-- Sidebar -->
            <aside class="col-lg-4 sidebar sidebar--right">

                <!-- Widget Popular Posts -->
                <aside class="widget widget-popular-posts">
                    <h4 class="widget-title">محبوب ترین مقالات</h4>
                    <ul class="post-list-small">
                        {% for blog in blog_view %}
                            <li class="post-list-small__item">
                                <article class="post-list-small__entry clearfix">
                                    <div class="post-list-small__img-holder">
                                        <div class="thumb-container thumb-100">
                                            <a href="{% url 'main:blog_detail' blog.id %}">
                                                <img data-src="{{ blog.cover_image.url }}"
                                                     src="{{ blog.cover_image.url }}" alt="{{ blog.cover_alt }}"
                                                     class="post-list-small__img--rounded lazyload">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="post-list-small__body">
                                        <h3 class="post-list-small__entry-title">
                                            <a href="{% url 'main:blog_detail' blog.id %}">{{ blog.title }}</a>
                                        </h3>
                                        <ul class="entry__meta">
                                            <li class="entry__meta-author">
                                                <span>نویسنده:</span>
                                                <a>{{ blog.author }}</a>
                                            </li>
                                            <li class="entry__meta-date">
                                                {{ blog.published_date }}
                                            </li>
                                        </ul>
                                    </div>
                                </article>
                            </li>
                        {% endfor %}


                    </ul>
                </aside> <!-- end widget popular posts -->

                <aside class="widget widget_media_image">
                    <a>
                        <img src="{{ media_url }}img/content/mag-1.jpg" alt="">
                    </a>
                </aside> <!-- end widget ad 300 -->


            </aside> <!-- end sidebar -->

        </div> <!-- end content -->
    </div> <!-- end main container -->
{% endblock %}

templates/page/main/categories.html
{% extends 'parent/base.html' %}
{% block title %}
    دسته بندی ها
{% endblock %}

{% block content %}
    <div class="container">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">خانه</a>
            </li>
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">اخبار</a>
            </li>
            <li class="breadcrumbs__item breadcrumbs__item--current">
                تکنولوژی
            </li>
        </ul>
    </div>


    <div class="main-container container" id="main-container">

        <!-- Content -->
        <div class="row">

            <!-- Posts -->
            <div class="col-lg-8 blog__content mb-72">
                <h1 class="page-title">{{ category.name }}</h1>

                <div class="row card-row">
                    {% for blog in category.blog_category.all %}
                        <div class="col-md-6">
                            <article class="entry card">
                                <div class="entry__img-holder card__img-holder">
                                    <a href="{% url 'main:blog_detail' blog.id %}">
                                        <div class="thumb-container thumb-70">
                                            <img data-src="{{ blog.cover_image.url }}" src="{{ blog.cover_image.url }}"
                                                 class="entry__img lazyload" alt="{{ blog.cover_alt }}"/>
                                        </div>
                                    </a>
                                    <a href="{% url 'main:blog_detail' blog.id %}"
                                       class="entry__meta-category entry__meta-category--label entry__meta-category--align-in-corner entry__meta-category--violet">
                                        {% for tag in blog.tag_blog.all %}
                                            {{ tag.tag_name }}
                                        {% endfor %}
                                    </a>
                                </div>

                                <div class="entry__body card__body">
                                    <div class="entry__header">

                                        <h2 class="entry__title">
                                            <a href="{% url 'main:blog_detail' blog.id %}">{{ blog.title }}</a>
                                        </h2>
                                        <ul class="entry__meta">
                                            <li class="entry__meta-author">
                                                <span>نویسنده:</span>
                                                <a>{{ blog.author }}</a>
                                            </li>
                                            <li class="entry__meta-date">
                                                {{ blog.published_date }}
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="entry__excerpt">
                                        <p>{{ blog.text | safe |linebreaksbr|truncatewords_html:30 }}</p>
                                    </div>
                                </div>
                            </article>
                        </div>
                    {% endfor %}
                </div>
            </div> <!-- end posts -->

            <!-- Sidebar -->
            <aside class="col-lg-4 sidebar sidebar--right">

                <!-- Widget Popular Posts -->
                <aside class="widget widget-popular-posts">
                    <h4 class="widget-title">محبوب ترین مقالات</h4>
                    <ul class="post-list-small">
                        {% for blog in blog_view %}
                            <li class="post-list-small__item">
                                <article class="post-list-small__entry clearfix">
                                    <div class="post-list-small__img-holder">
                                        <div class="thumb-container thumb-100">
                                            <a href="{% url 'main:blog_detail' blog.id %}">
                                                <img data-src="{{ blog.cover_image.url }}" src="{{ blog.cover_image.url }}" alt="{{ blog.cover_alt }}"
                                                     class="post-list-small__img--rounded lazyload">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="post-list-small__body">
                                        <h3 class="post-list-small__entry-title">
                                            <a href="{% url 'main:blog_detail' blog.id %}">{{ blog.title }}</a>
                                        </h3>
                                        <ul class="entry__meta">
                                            <li class="entry__meta-author">
                                                <span>نویسنده:</span>
                                                <a>{{ blog.author }}</a>
                                            </li>
                                            <li class="entry__meta-date">
                                                {{ blog.published_date }}
                                            </li>
                                        </ul>
                                    </div>
                                </article>
                            </li>
                        {% endfor %}

                    </ul>

                </aside> <!-- end widget popular posts -->


                <!-- Widget Ad 300 -->
                <aside class="widget widget_media_image">
                    <a>
                        <img src="{{ media_url }}img/content/mag-1.jpg" alt="">
                    </a>
                </aside> <!-- end widget ad 300 -->

            </aside> <!-- end sidebar -->

        </div> <!-- end content -->
    </div> <!-- end main container -->
{% endblock %}

templates/page/main/contact.html
{% extends 'parent/base.html' %}
{% block title %}
    تماس با ما
{% endblock %}

{% block content %}
    <!-- Breadcrumbs -->
    <div class="container">
        <ul class="breadcrumbs">
            <li class="breadcrumbs__item">
                <a href="{% url 'main:index' %}" class="breadcrumbs__url">خانه</a>
            </li>
            <li class="breadcrumbs__item breadcrumbs__item--current">
                تماس با ما
            </li>
        </ul>
    </div>

    <div class="main-container container" id="main-container">
        <!-- post content -->
        <div class="blog__content mb-72">
            <h1 class="page-title">تماس با ما</h1>

            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <h4>با ما تماس بگیرید</h4>
                    <p>{{ site_settings.text_contact|safe }}</p>
                    <ul class="contact-items">
                        <li class="contact-item">
                            <address>{{ site_settings.address }}</address>
                        </li>
                        <li class="contact-item">{{ site_settings.phone_number }}</li>
                        <li class="contact-item">{{ site_settings.email }}</li>
                    </ul>

                    <!-- Contact Form -->


                </div>
            </div>
        </div> <!-- end post content -->
    </div> <!-- end main container -->
{% endblock %}