Article/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor', include('ckeditor_uploader.urls')),
                  path('account/', include('account.urls', namespace='account')),
                  path('', include('main.urls', namespace='main'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    # path('recovery_pass/',views.RecoveryPass.as_view(), name='recovery_pass'),
    # path('active_code/', views.ActiveCode.as_view(), name='active_code'),
    # path('change_pass/',views.ChangePassView.as_view(), name='change_pass')
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('blog/<blog_id>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('category/<category_id>/', views.CategoryView.as_view(), name='category'),
    path('404/', views.NotFoundView.as_view(), name='404'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.CantactView.as_view(), name='contact')

]

templates/partial/header.html
<!-- Bg Overlay -->
<div class="content-overlay"></div>

<!-- Sidenav -->
<header class="sidenav" id="sidenav">

    <!-- close -->
    <div class="sidenav__close">
        <button class="sidenav__close-button" id="sidenav__close-button" aria-label="close sidenav">
            <i class="ui-close sidenav__close-icon"></i>
        </button>
    </div>

    <!-- Nav -->
    <nav class="sidenav__menu-container">
        <ul class="sidenav__menu" role="menubar">
            <li>
                <a href="{% url 'main:index' %}" class="sidenav__menu-url">صفحه اصلی</a>
            </li>
            <li>
                <a href="#" class="sidenav__menu-url">صفحات</a>
                <button class="sidenav__menu-toggle" aria-haspopup="true" aria-label="Open dropdown"><i
                        class="ui-arrow-down"></i></button>
                <ul class="sidenav__menu-dropdown">
                    <li><a href="{% url 'main:about' %}" class="sidenav__menu-url">درباره ما</a></li>
                    <li><a href="{% url 'main:contact' %}" class="sidenav__menu-url">تماس با ما</a></li>
                    <li><a href="{% url 'account:login' %}" class="sidenav__menu-url">ورود</a></li>
                    <li><a href="{% url 'account:register' %}" class="sidenav__menu-url">ثبت نام</a></li>
                </ul>
            </li>

            <!-- Categories -->
        </ul>
    </nav>


</header> <!-- end sidenav -->

<main class="main oh" id="main">

    <!-- Top Bar -->
    <div class="top-bar d-none d-lg-block">
        <div class="container">
            <div class="row">

                <!-- Top menu -->
                <div class="col-lg-6">
                    <ul class="top-menu">
                        <li><a href="{% url 'main:about' %}">درباره ما</a></li>
                        <li><a href="{% url 'main:contact' %}">تماس با ما</a></li>
                        <li><a href="{% url 'account:login' %}">ورود</a></li>
                        <li><a href="{% url 'account:register' %}">ثبت نام</a></li>
                    </ul>
                </div>

                <!-- Socials -->


            </div>
        </div>
    </div> <!-- end top bar -->

    <!-- Navigation -->
    <header class="nav">

        <div class="nav__holder nav--sticky">
            <div class="container relative">
                <div class="flex-parent">

                    <!-- Side Menu Button -->
                    <button class="nav-icon-toggle" id="nav-icon-toggle" aria-label="Open side menu">
                            <span class="nav-icon-toggle__box">
                                <span class="nav-icon-toggle__inner"></span>
                            </span>
                    </button>

                    <!-- Logo -->
                    <a href="{% url 'main:index' %}" class="logo">
                        <img style="width: 40px;height: 40px" class="logo__img" src="{{ site_settings.logo_url }}" alt="logo">
                    </a>

                    <!-- Nav-wrap -->
                    <nav class="flex-child nav__wrap d-none d-lg-block">
                        <ul class="nav__menu">

                            <li class="active">
                                <a href="{% url 'main:index' %}">صفحه اصلی</a>
                            </li>
                            <li class="nav__dropdown">
                                <a href="#">صفحات</a>
                                <ul class="nav__dropdown-menu">
                                    <li><a href="{% url 'main:about' %}">درباره ما</a></li>
                                    <li><a href="{% url 'main:contact' %}">تماس با ما</a></li>
                                    <li><a href="{% url 'account:login' %}">ورود</a></li>
                                    <li><a href="{% url 'account:register' %}">ثبت نام</a></li>
                                </ul>
                            </li>
                        </ul> <!-- end menu -->
                    </nav> <!-- end nav-wrap -->
                    <!-- Nav Right -->
                    <div class="nav__right">
                        <!-- Search -->
                        <div class="nav__right-item nav__search">
                            <a href="#" class="nav__search-trigger" id="nav__search-trigger">
                                <i class="ui-search nav__search-trigger-icon"></i>
                            </a>
                            <div class="nav__search-box" id="nav__search-box">
                                <form class="nav__search-form" action="{% url 'main:search' %}">
                                    <input type="text" placeholder="جستجو مقالات" class="nav__search-input" id="q"
                                           name="q">
                                    <button type="submit" class="search-button btn btn-lg btn-color btn-button">
                                        <i class="ui-search nav__search-icon"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div> <!-- end nav right -->
                </div> <!-- end flex-parent -->
            </div> <!-- end container -->
        </div>
    </header> 